# Site information (Default language - Russian)
site_name: "Zero Token (роман) - Antimortine | Психологический техно-триллер"
site_url: "https://Antimortine.github.io/zero-token-book"
site_author: "Antimortine"
site_description: "Читайте онлайн роман Zero Token (Автор: Antimortine). Психологический техно-триллер об одиноком программисте Алексе, его ИИ-помощнике и опасной тайне Nexus AI."

# Repository info
repo_url: "https://github.com/Antimortine/zero-token-book/"
repo_name: "zero-token-book"
edit_uri: ""

# Theme Configuration
theme:
  name: material
  language: ru
  palette:
    scheme: slate
    primary: teal
    accent: purple
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono

# Markdown Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
      toc_depth: 3

# Plugins Configuration - Minimal REQUIRED i18n config
plugins:
  - search
  - i18n: # Используем имя 'i18n'
      # Возвращаем ОБЯЗАТЕЛЬНЫЕ опции:
      languages: # Правильный формат - список
        - ru
        - en
      default_language: ru
      docs_structure: folder # Указываем структуру папок

# NO external languages: section
# NO extra: section
# NO nav: section (MkDocs will build nav from file structure)