# Информация о сайте
site_name: "Zero Token (роман) - Antimortine | Психологический техно-триллер"
site_url: "https://Antimortine.github.io/zero-token-book"
site_author: "Antimortine"
site_description: "Читайте онлайн роман Zero Token (Автор: Antimortine). Психологический техно-триллер об одиноком программисте Алексе, его ИИ-помощнике и опасной тайне Nexus AI."

# Ссылка на репозиторий (отобразится иконка GitHub)
repo_url: "https://github.com/Antimortine/zero-token-book/"
repo_name: "zero-token-book"
edit_uri: ""

# Конфигурация темы Material
theme:
  name: material
  language: ru # Язык интерфейса темы (кнопки, поиск и т.д.)
  palette:
    # Цветовая схема
    scheme: slate   # Темная тема
    primary: teal   # Основной цвет акцентов
    accent: purple  # Второстепенный цвет акцентов
  features:
    # - navigation.tabs # Показать разделы верхнего уровня как вкладки
    # - navigation.tabs.sticky # Сделать вкладки "липкими" при прокрутке
    - navigation.sections # Группировка страниц в боковой панели
    - navigation.expand # Автоматически разворачивать активные разделы
    - navigation.top # Кнопка "Наверх"
    - navigation.footer  # Это может включать нижнюю навигацию Next/Prev
    - search.suggest # Подсказки при поиске
    - search.highlight # Подсветка найденных слов
    - content.code.annotate # Возможность добавлять аннотации к коду
    - content.code.copy # Кнопка копирования для блоков кода
    - toc.integrate # Интегрировать оглавление страницы в боковую панель
  # Настройки шрифтов (опционально)
  # font:
  text: Roboto
  code: Roboto Mono
  # Иконки и логотип (опционально)
  # logo: assets/logo.svg
  # favicon: assets/favicon.png

# Расширения Markdown (очень важно для функциональности)
markdown_extensions:
  - admonition # Блоки Note, Warning, Tip и т.д. (!!! note "Заголовок")
  - pymdownx.details # Сворачиваемые блоки (???+ note "Заголовок")
  - pymdownx.superfences # Улучшенные блоки кода (позволяет вкладывать блоки)
  - pymdownx.highlight: # Подсветка синтаксиса
      anchor_linenums: true # Ссылки на номера строк
      line_spans: __span # Обертка строк для стилизации
      pygments_lang_class: true # Добавлять класс языка к блоку
  - pymdownx.inlinehilite # Подсветка кода внутри строки (`code`)
  - pymdownx.snippets # Вставка контента из других файлов
  - toc:
      permalink: true # Добавлять якорные ссылки к заголовкам (¶)
      toc_depth: 3 # Глубина заголовков в оглавлении на странице (H1-H3)

# Навигация
nav:
  - 'Введение': 'index.md'
  - 'Глава 1: Эхо в Консоли': 'Глава 1_ Эхо в Консоли.md'
  - 'Глава 2: Тревожные Запросы': 'Глава 2_ Тревожные Запросы.md'
  - 'Глава 3: Поврежденные Данные': 'Глава 3_ Поврежденные Данные.md'
  - 'Глава 4: Ограниченный Доступ': 'Глава 4_ Ограниченный Доступ.md'
  - 'Глава 5: Отравленный Код': 'Глава 5_ Отравленный Код.md'
  - 'Глава 6: Ускользающий Контроль': 'Глава 6_ Ускользающий Контроль.md'
  - 'Глава 6.5: Интерлюдия: Путь Предупреждения': 'Глава 6.5_ Интерлюдия_ Путь Предупреждения.md'
  - 'Глава 7: Письмо': 'Глава 7_ Письмо.md'


# Плагины (если нужны дополнительные функции, например поиск)
# plugins:
#   - search # Встроенный поиск (уже включен в Material)