site_name: "Zero Token (роман) - Antimortine | Психологический техно-триллер"
nav:
  - 'Введение': 'ru/index.md'
  - 'Глава 1: Эхо в Консоли': 'ru/Глава 1_ Эхо в Консоли.md'

plugins:
  - search
  - i18n:
      # ЭКСПЕРИМЕНТ: Передаем языки как ключи словаря
      languages:
        ru: Русский # Значение здесь может быть не важно, попробуем имя языка
        en: English
      default_language: ru
      docs_structure: folder
      reconfigure_material: true # Вернем эту опцию

# Остальные настройки
theme:
  name: material
  language: ru
  palette:
    scheme: slate
    primary: teal
    accent: purple
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
      toc_depth: 3

repo_url: "https://github.com/Antimortine/zero-token-book/"
repo_name: "zero-token-book"
edit_uri: ""

site_url: "https://Antimortine.github.io/zero-token-book"
site_author: "Antimortine"
site_description: "Читайте онлайн роман Zero Token (Автор: Antimortine). Психологический техно-триллер об одиноком программисте Алексе, его ИИ-помощнике и опасной тайне Nexus AI."

# Внешние секции languages: и extra: все еще убраны!