---
name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - master # Или 'main', если это твоя основная ветка

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout code с опциями для очистки
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Получить всю историю, может помочь с кэшем
          clean: true    # Явно очистить рабочую директорию перед checkout

      # Шаг 2 (НОВЫЙ): Вывод содержимого mkdocs.yml для отладки
      - name: Display mkdocs.yml content
        run: |
          echo "--- Content of mkdocs.yml used by runner ---"
          cat mkdocs.yml
          echo "--- End of mkdocs.yml content ---"

      # Шаг 3: Настройка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Оставляем Python 3.11

      # Шаг 4: Установка зависимостей
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Шаг 5: Проверка Entry Points и импорта плагина
      - name: Check MkDocs Plugin Entry Points and Import
        run: |
          echo "--- Checking Entry Points ---"
          python -c "import sys; from importlib.metadata import entry_points; discovered_plugins = entry_points(group='mkdocs.plugins'); print('Found entry points:') if discovered_plugins else print('No entry points found.'); [print(f'- {ep.name} = {ep.value}') for ep in discovered_plugins if discovered_plugins]"
          echo "--- Attempting Direct Import ---"
          python - <<EOF
          import sys
          try:
              from mkdocs_static_i18n.plugin import I18n
              print("OK: mkdocs_static_i18n imported successfully.")
              sys.exit(0)
          except ImportError as e:
              print(f"FAIL: Could not import mkdocs_static_i18n: {e}")
              sys.exit(1)
          except Exception as e_gen:
              print(f"FAIL: General error during import attempt: {e_gen}")
              sys.exit(1)
          EOF

      # Шаг 6: Сборка сайта
      - name: Build MkDocs site
        run: python -m mkdocs build --verbose --clean
        # Проверяем, возникает ли ошибка здесь

      # Шаг 7: Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        run: python -m mkdocs gh-deploy --force --clean --verbose
        # Выполняется, только если сборка прошла успешно